[package]
name = "target"
version = "0.1.0"
authors = ["Gard Cappelen <gard@cappelendigital.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
detour = "0.7.1"